### ISSUE TITLE
logo contribution

### ISSUE THREAD

**Issue by reallinfo** [vladgolubev/gh-shipit#209]
hi @vladgolubev 

I contribute to open source projects that do not have logo. I wanted to design a logo for this repo. Please tell me what you think. 

![gh-shipit](https://user-images.githubusercontent.com/36298335/56760307-9514a880-67a3-11e9-9cb0-26a6b9c4adb9.jpg)

**Comment by vladgolubev** [comment]
Hey @reallinfo 

That's awesome! 👍🏻 Thanks for the contribution! 🙌🏻

I like the first variant (horizontal). Do you have an svg or a hi-res png so I can add it to the README?

**Comment by reallinfo** [comment]
of course, I'll send a pr soon. I am glad you like it :)

**Comment by reallinfo** [comment]
I sent a pr. Please feel free to contact me for other projects. Thanks!
